version: '3'

services:
  
  node:
    image: epik/go-epik
    build:
      context: ./docker
    ports:
      - '1234:1234'
      - '1347:1347'
      - '2345:2345'
    volumes:
      - .:/go-epik
    environment:
      - REGION=China
    command: bash docker/scripts/epik.sh
